package com.ancun.boss.business.persistence.module;

import java.util.Date;

public class BizUserInfo {

    /**
     * 套餐名称
     */
    private String taocanName;

    /**
     * 注册来源
     */
    private String isignupSource;

    public String getTaocanName() {
        return taocanName;
    }

    public void setTaocanName(String taocanName) {
        this.taocanName = taocanName;
    }

    public String getIsignupSource() {
        return isignupSource;
    }

    public void setIsignupSource(String isignupSource) {
        this.isignupSource = isignupSource;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.USER_NO
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.PASSWD
     *
     * @mbggenerated
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.USER_TYPE
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.ENT_NO
     *
     * @mbggenerated
     */
    private String entNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.BIZ_NO
     *
     * @mbggenerated
     */
    private String bizNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.TCID
     *
     * @mbggenerated
     */
    private Long tcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.ORG_NO
     *
     * @mbggenerated
     */
    private String orgNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.RPCODE
     *
     * @mbggenerated
     */
    private String rpcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.CITY_CODE
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.RECTIP
     *
     * @mbggenerated
     */
    private String rectip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.INTIME
     *
     * @mbggenerated
     */
    private Date intime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.INSOURCE
     *
     * @mbggenerated
     */
    private String insource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.OFFSOURCE
     *
     * @mbggenerated
     */
    private String offsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.OFFTIME
     *
     * @mbggenerated
     */
    private Date offtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.CALLER_VOICE
     *
     * @mbggenerated
     */
    private String callerVoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.CALLED_VOICE
     *
     * @mbggenerated
     */
    private String calledVoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.CALLER_RECORD
     *
     * @mbggenerated
     */
    private String callerRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.CALLED_RECORD
     *
     * @mbggenerated
     */
    private String calledRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.PHONETYPE
     *
     * @mbggenerated
     */
    private String phonetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.DEFAULTPWDFLAG
     *
     * @mbggenerated
     */
    private String defaultpwdflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.ISREFUND
     *
     * @mbggenerated
     */
    private String isrefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.REFUNDAMOUNT
     *
     * @mbggenerated
     */
    private Double refundamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.REFUNDREMARK
     *
     * @mbggenerated
     */
    private String refundremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.SMS_LOGIN
     *
     * @mbggenerated
     */
    private String smsLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.BUSINESSTYPE
     *
     * @mbggenerated
     */
    private String businesstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.CALLERFLAG
     *
     * @mbggenerated
     */
    private String callerflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.CALLEDFLAG
     *
     * @mbggenerated
     */
    private String calledflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.FAX
     *
     * @mbggenerated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.FULLPACKAGE
     *
     * @mbggenerated
     */
    private String fullpackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.UNIQUENO
     *
     * @mbggenerated
     */
    private String uniqueno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_INFO.OPERATION
     *
     * @mbggenerated
     */
    private String operation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.ID
     *
     * @return the value of BIZ_USER_INFO.ID
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.ID
     *
     * @param id the value for BIZ_USER_INFO.ID
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.USER_NO
     *
     * @return the value of BIZ_USER_INFO.USER_NO
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.USER_NO
     *
     * @param userNo the value for BIZ_USER_INFO.USER_NO
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.PASSWD
     *
     * @return the value of BIZ_USER_INFO.PASSWD
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.PASSWD
     *
     * @param passwd the value for BIZ_USER_INFO.PASSWD
     * @mbggenerated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.USER_TYPE
     *
     * @return the value of BIZ_USER_INFO.USER_TYPE
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.USER_TYPE
     *
     * @param userType the value for BIZ_USER_INFO.USER_TYPE
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.ENT_NO
     *
     * @return the value of BIZ_USER_INFO.ENT_NO
     * @mbggenerated
     */
    public String getEntNo() {
        return entNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.ENT_NO
     *
     * @param entNo the value for BIZ_USER_INFO.ENT_NO
     * @mbggenerated
     */
    public void setEntNo(String entNo) {
        this.entNo = entNo == null ? null : entNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.ACCOUNT_TYPE
     *
     * @return the value of BIZ_USER_INFO.ACCOUNT_TYPE
     * @mbggenerated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.ACCOUNT_TYPE
     *
     * @param accountType the value for BIZ_USER_INFO.ACCOUNT_TYPE
     * @mbggenerated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.BIZ_NO
     *
     * @return the value of BIZ_USER_INFO.BIZ_NO
     * @mbggenerated
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.BIZ_NO
     *
     * @param bizNo the value for BIZ_USER_INFO.BIZ_NO
     * @mbggenerated
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.TCID
     *
     * @return the value of BIZ_USER_INFO.TCID
     * @mbggenerated
     */
    public Long getTcid() {
        return tcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.TCID
     *
     * @param tcid the value for BIZ_USER_INFO.TCID
     * @mbggenerated
     */
    public void setTcid(Long tcid) {
        this.tcid = tcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.ORG_NO
     *
     * @return the value of BIZ_USER_INFO.ORG_NO
     * @mbggenerated
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.ORG_NO
     *
     * @param orgNo the value for BIZ_USER_INFO.ORG_NO
     * @mbggenerated
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo == null ? null : orgNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.STATUS
     *
     * @return the value of BIZ_USER_INFO.STATUS
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.STATUS
     *
     * @param status the value for BIZ_USER_INFO.STATUS
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.RPCODE
     *
     * @return the value of BIZ_USER_INFO.RPCODE
     * @mbggenerated
     */
    public String getRpcode() {
        return rpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.RPCODE
     *
     * @param rpcode the value for BIZ_USER_INFO.RPCODE
     * @mbggenerated
     */
    public void setRpcode(String rpcode) {
        this.rpcode = rpcode == null ? null : rpcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.CITY_CODE
     *
     * @return the value of BIZ_USER_INFO.CITY_CODE
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.CITY_CODE
     *
     * @param cityCode the value for BIZ_USER_INFO.CITY_CODE
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.PHONE
     *
     * @return the value of BIZ_USER_INFO.PHONE
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.PHONE
     *
     * @param phone the value for BIZ_USER_INFO.PHONE
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.RECTIP
     *
     * @return the value of BIZ_USER_INFO.RECTIP
     * @mbggenerated
     */
    public String getRectip() {
        return rectip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.RECTIP
     *
     * @param rectip the value for BIZ_USER_INFO.RECTIP
     * @mbggenerated
     */
    public void setRectip(String rectip) {
        this.rectip = rectip == null ? null : rectip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.INTIME
     *
     * @return the value of BIZ_USER_INFO.INTIME
     * @mbggenerated
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.INTIME
     *
     * @param intime the value for BIZ_USER_INFO.INTIME
     * @mbggenerated
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.INSOURCE
     *
     * @return the value of BIZ_USER_INFO.INSOURCE
     * @mbggenerated
     */
    public String getInsource() {
        return insource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.INSOURCE
     *
     * @param insource the value for BIZ_USER_INFO.INSOURCE
     * @mbggenerated
     */
    public void setInsource(String insource) {
        this.insource = insource == null ? null : insource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.OFFSOURCE
     *
     * @return the value of BIZ_USER_INFO.OFFSOURCE
     * @mbggenerated
     */
    public String getOffsource() {
        return offsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.OFFSOURCE
     *
     * @param offsource the value for BIZ_USER_INFO.OFFSOURCE
     * @mbggenerated
     */
    public void setOffsource(String offsource) {
        this.offsource = offsource == null ? null : offsource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.OFFTIME
     *
     * @return the value of BIZ_USER_INFO.OFFTIME
     * @mbggenerated
     */
    public Date getOfftime() {
        return offtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.OFFTIME
     *
     * @param offtime the value for BIZ_USER_INFO.OFFTIME
     * @mbggenerated
     */
    public void setOfftime(Date offtime) {
        this.offtime = offtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.CALLER_VOICE
     *
     * @return the value of BIZ_USER_INFO.CALLER_VOICE
     * @mbggenerated
     */
    public String getCallerVoice() {
        return callerVoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.CALLER_VOICE
     *
     * @param callerVoice the value for BIZ_USER_INFO.CALLER_VOICE
     * @mbggenerated
     */
    public void setCallerVoice(String callerVoice) {
        this.callerVoice = callerVoice == null ? null : callerVoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.CALLED_VOICE
     *
     * @return the value of BIZ_USER_INFO.CALLED_VOICE
     * @mbggenerated
     */
    public String getCalledVoice() {
        return calledVoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.CALLED_VOICE
     *
     * @param calledVoice the value for BIZ_USER_INFO.CALLED_VOICE
     * @mbggenerated
     */
    public void setCalledVoice(String calledVoice) {
        this.calledVoice = calledVoice == null ? null : calledVoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.CALLER_RECORD
     *
     * @return the value of BIZ_USER_INFO.CALLER_RECORD
     * @mbggenerated
     */
    public String getCallerRecord() {
        return callerRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.CALLER_RECORD
     *
     * @param callerRecord the value for BIZ_USER_INFO.CALLER_RECORD
     * @mbggenerated
     */
    public void setCallerRecord(String callerRecord) {
        this.callerRecord = callerRecord == null ? null : callerRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.CALLED_RECORD
     *
     * @return the value of BIZ_USER_INFO.CALLED_RECORD
     * @mbggenerated
     */
    public String getCalledRecord() {
        return calledRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.CALLED_RECORD
     *
     * @param calledRecord the value for BIZ_USER_INFO.CALLED_RECORD
     * @mbggenerated
     */
    public void setCalledRecord(String calledRecord) {
        this.calledRecord = calledRecord == null ? null : calledRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.PHONETYPE
     *
     * @return the value of BIZ_USER_INFO.PHONETYPE
     * @mbggenerated
     */
    public String getPhonetype() {
        return phonetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.PHONETYPE
     *
     * @param phonetype the value for BIZ_USER_INFO.PHONETYPE
     * @mbggenerated
     */
    public void setPhonetype(String phonetype) {
        this.phonetype = phonetype == null ? null : phonetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.DEFAULTPWDFLAG
     *
     * @return the value of BIZ_USER_INFO.DEFAULTPWDFLAG
     * @mbggenerated
     */
    public String getDefaultpwdflag() {
        return defaultpwdflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.DEFAULTPWDFLAG
     *
     * @param defaultpwdflag the value for BIZ_USER_INFO.DEFAULTPWDFLAG
     * @mbggenerated
     */
    public void setDefaultpwdflag(String defaultpwdflag) {
        this.defaultpwdflag = defaultpwdflag == null ? null : defaultpwdflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.ISREFUND
     *
     * @return the value of BIZ_USER_INFO.ISREFUND
     * @mbggenerated
     */
    public String getIsrefund() {
        return isrefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.ISREFUND
     *
     * @param isrefund the value for BIZ_USER_INFO.ISREFUND
     * @mbggenerated
     */
    public void setIsrefund(String isrefund) {
        this.isrefund = isrefund == null ? null : isrefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.REFUNDAMOUNT
     *
     * @return the value of BIZ_USER_INFO.REFUNDAMOUNT
     * @mbggenerated
     */
    public Double getRefundamount() {
        return refundamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.REFUNDAMOUNT
     *
     * @param refundamount the value for BIZ_USER_INFO.REFUNDAMOUNT
     * @mbggenerated
     */
    public void setRefundamount(Double refundamount) {
        this.refundamount = refundamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.REFUNDREMARK
     *
     * @return the value of BIZ_USER_INFO.REFUNDREMARK
     * @mbggenerated
     */
    public String getRefundremark() {
        return refundremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.REFUNDREMARK
     *
     * @param refundremark the value for BIZ_USER_INFO.REFUNDREMARK
     * @mbggenerated
     */
    public void setRefundremark(String refundremark) {
        this.refundremark = refundremark == null ? null : refundremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.SMS_LOGIN
     *
     * @return the value of BIZ_USER_INFO.SMS_LOGIN
     * @mbggenerated
     */
    public String getSmsLogin() {
        return smsLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.SMS_LOGIN
     *
     * @param smsLogin the value for BIZ_USER_INFO.SMS_LOGIN
     * @mbggenerated
     */
    public void setSmsLogin(String smsLogin) {
        this.smsLogin = smsLogin == null ? null : smsLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.EMAIL
     *
     * @return the value of BIZ_USER_INFO.EMAIL
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.EMAIL
     *
     * @param email the value for BIZ_USER_INFO.EMAIL
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.BUSINESSTYPE
     *
     * @return the value of BIZ_USER_INFO.BUSINESSTYPE
     * @mbggenerated
     */
    public String getBusinesstype() {
        return businesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.BUSINESSTYPE
     *
     * @param businesstype the value for BIZ_USER_INFO.BUSINESSTYPE
     * @mbggenerated
     */
    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype == null ? null : businesstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.CALLERFLAG
     *
     * @return the value of BIZ_USER_INFO.CALLERFLAG
     * @mbggenerated
     */
    public String getCallerflag() {
        return callerflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.CALLERFLAG
     *
     * @param callerflag the value for BIZ_USER_INFO.CALLERFLAG
     * @mbggenerated
     */
    public void setCallerflag(String callerflag) {
        this.callerflag = callerflag == null ? null : callerflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.CALLEDFLAG
     *
     * @return the value of BIZ_USER_INFO.CALLEDFLAG
     * @mbggenerated
     */
    public String getCalledflag() {
        return calledflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.CALLEDFLAG
     *
     * @param calledflag the value for BIZ_USER_INFO.CALLEDFLAG
     * @mbggenerated
     */
    public void setCalledflag(String calledflag) {
        this.calledflag = calledflag == null ? null : calledflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.REMARK
     *
     * @return the value of BIZ_USER_INFO.REMARK
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.REMARK
     *
     * @param remark the value for BIZ_USER_INFO.REMARK
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.FAX
     *
     * @return the value of BIZ_USER_INFO.FAX
     * @mbggenerated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.FAX
     *
     * @param fax the value for BIZ_USER_INFO.FAX
     * @mbggenerated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.FULLPACKAGE
     *
     * @return the value of BIZ_USER_INFO.FULLPACKAGE
     * @mbggenerated
     */
    public String getFullpackage() {
        return fullpackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.FULLPACKAGE
     *
     * @param fullpackage the value for BIZ_USER_INFO.FULLPACKAGE
     * @mbggenerated
     */
    public void setFullpackage(String fullpackage) {
        this.fullpackage = fullpackage == null ? null : fullpackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.UNIQUENO
     *
     * @return the value of BIZ_USER_INFO.UNIQUENO
     * @mbggenerated
     */
    public String getUniqueno() {
        return uniqueno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.UNIQUENO
     *
     * @param uniqueno the value for BIZ_USER_INFO.UNIQUENO
     * @mbggenerated
     */
    public void setUniqueno(String uniqueno) {
        this.uniqueno = uniqueno == null ? null : uniqueno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_INFO.OPERATION
     *
     * @return the value of BIZ_USER_INFO.OPERATION
     * @mbggenerated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_INFO.OPERATION
     *
     * @param operation the value for BIZ_USER_INFO.OPERATION
     * @mbggenerated
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }
}