package com.ancun.boss.business.persistence.module;

import com.thoughtworks.xstream.annotations.XStreamAlias;

import java.util.Date;

@XStreamAlias("bizUserLifeCircle")
public class BizUserLifeCircle {

    /**
     * 套餐名称
     */
    private String tcName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.USER_NO
     *
     * @mbggenerated
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.USER_TYPE
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.ENT_NO
     *
     * @mbggenerated
     */
    private String entNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.BIZ_NO
     *
     * @mbggenerated
     */
    private String bizNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.TCID
     *
     * @mbggenerated
     */
    private Long tcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.ORG_NO
     *
     * @mbggenerated
     */
    private String orgNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.RPCODE
     *
     * @mbggenerated
     */
    private String rpcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.CITY_CODE
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.RECTIP
     *
     * @mbggenerated
     */
    private String rectip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.OPEN_CANCEL
     *
     * @mbggenerated
     */
    private String openCancel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.SOURCE
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.TIMERS
     *
     * @mbggenerated
     */
    private Date timers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.CALLER_VOICE
     *
     * @mbggenerated
     */
    private String callerVoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.CALLED_VOICE
     *
     * @mbggenerated
     */
    private String calledVoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.CALLER_RECORD
     *
     * @mbggenerated
     */
    private String callerRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.CALLED_RECORD
     *
     * @mbggenerated
     */
    private String calledRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_LIFE_CIRCLE.PHONETYPE
     *
     * @mbggenerated
     */
    private String phonetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.USER_NO
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.USER_NO
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.USER_NO
     *
     * @param userNo the value for BIZ_USER_LIFE_CIRCLE.USER_NO
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.USER_TYPE
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.USER_TYPE
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.USER_TYPE
     *
     * @param userType the value for BIZ_USER_LIFE_CIRCLE.USER_TYPE
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.ENT_NO
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.ENT_NO
     * @mbggenerated
     */
    public String getEntNo() {
        return entNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.ENT_NO
     *
     * @param entNo the value for BIZ_USER_LIFE_CIRCLE.ENT_NO
     * @mbggenerated
     */
    public void setEntNo(String entNo) {
        this.entNo = entNo == null ? null : entNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.ACCOUNT_TYPE
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.ACCOUNT_TYPE
     * @mbggenerated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.ACCOUNT_TYPE
     *
     * @param accountType the value for BIZ_USER_LIFE_CIRCLE.ACCOUNT_TYPE
     * @mbggenerated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.BIZ_NO
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.BIZ_NO
     * @mbggenerated
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.BIZ_NO
     *
     * @param bizNo the value for BIZ_USER_LIFE_CIRCLE.BIZ_NO
     * @mbggenerated
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.TCID
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.TCID
     * @mbggenerated
     */
    public Long getTcid() {
        return tcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.TCID
     *
     * @param tcid the value for BIZ_USER_LIFE_CIRCLE.TCID
     * @mbggenerated
     */
    public void setTcid(Long tcid) {
        this.tcid = tcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.ORG_NO
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.ORG_NO
     * @mbggenerated
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.ORG_NO
     *
     * @param orgNo the value for BIZ_USER_LIFE_CIRCLE.ORG_NO
     * @mbggenerated
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo == null ? null : orgNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.RPCODE
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.RPCODE
     * @mbggenerated
     */
    public String getRpcode() {
        return rpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.RPCODE
     *
     * @param rpcode the value for BIZ_USER_LIFE_CIRCLE.RPCODE
     * @mbggenerated
     */
    public void setRpcode(String rpcode) {
        this.rpcode = rpcode == null ? null : rpcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.CITY_CODE
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.CITY_CODE
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.CITY_CODE
     *
     * @param cityCode the value for BIZ_USER_LIFE_CIRCLE.CITY_CODE
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.PHONE
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.PHONE
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.PHONE
     *
     * @param phone the value for BIZ_USER_LIFE_CIRCLE.PHONE
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.RECTIP
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.RECTIP
     * @mbggenerated
     */
    public String getRectip() {
        return rectip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.RECTIP
     *
     * @param rectip the value for BIZ_USER_LIFE_CIRCLE.RECTIP
     * @mbggenerated
     */
    public void setRectip(String rectip) {
        this.rectip = rectip == null ? null : rectip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.OPEN_CANCEL
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.OPEN_CANCEL
     * @mbggenerated
     */
    public String getOpenCancel() {
        return openCancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.OPEN_CANCEL
     *
     * @param openCancel the value for BIZ_USER_LIFE_CIRCLE.OPEN_CANCEL
     * @mbggenerated
     */
    public void setOpenCancel(String openCancel) {
        this.openCancel = openCancel == null ? null : openCancel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.SOURCE
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.SOURCE
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.SOURCE
     *
     * @param source the value for BIZ_USER_LIFE_CIRCLE.SOURCE
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.TIMERS
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.TIMERS
     * @mbggenerated
     */
    public Date getTimers() {
        return timers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.TIMERS
     *
     * @param timers the value for BIZ_USER_LIFE_CIRCLE.TIMERS
     * @mbggenerated
     */
    public void setTimers(Date timers) {
        this.timers = timers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.CALLER_VOICE
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.CALLER_VOICE
     * @mbggenerated
     */
    public String getCallerVoice() {
        return callerVoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.CALLER_VOICE
     *
     * @param callerVoice the value for BIZ_USER_LIFE_CIRCLE.CALLER_VOICE
     * @mbggenerated
     */
    public void setCallerVoice(String callerVoice) {
        this.callerVoice = callerVoice == null ? null : callerVoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.CALLED_VOICE
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.CALLED_VOICE
     * @mbggenerated
     */
    public String getCalledVoice() {
        return calledVoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.CALLED_VOICE
     *
     * @param calledVoice the value for BIZ_USER_LIFE_CIRCLE.CALLED_VOICE
     * @mbggenerated
     */
    public void setCalledVoice(String calledVoice) {
        this.calledVoice = calledVoice == null ? null : calledVoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.CALLER_RECORD
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.CALLER_RECORD
     * @mbggenerated
     */
    public String getCallerRecord() {
        return callerRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.CALLER_RECORD
     *
     * @param callerRecord the value for BIZ_USER_LIFE_CIRCLE.CALLER_RECORD
     * @mbggenerated
     */
    public void setCallerRecord(String callerRecord) {
        this.callerRecord = callerRecord == null ? null : callerRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.CALLED_RECORD
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.CALLED_RECORD
     * @mbggenerated
     */
    public String getCalledRecord() {
        return calledRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.CALLED_RECORD
     *
     * @param calledRecord the value for BIZ_USER_LIFE_CIRCLE.CALLED_RECORD
     * @mbggenerated
     */
    public void setCalledRecord(String calledRecord) {
        this.calledRecord = calledRecord == null ? null : calledRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.UPDATE_TIME
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.UPDATE_TIME
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.UPDATE_TIME
     *
     * @param updateTime the value for BIZ_USER_LIFE_CIRCLE.UPDATE_TIME
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.REMARK
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.REMARK
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.REMARK
     *
     * @param remark the value for BIZ_USER_LIFE_CIRCLE.REMARK
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_LIFE_CIRCLE.PHONETYPE
     *
     * @return the value of BIZ_USER_LIFE_CIRCLE.PHONETYPE
     * @mbggenerated
     */
    public String getPhonetype() {
        return phonetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_LIFE_CIRCLE.PHONETYPE
     *
     * @param phonetype the value for BIZ_USER_LIFE_CIRCLE.PHONETYPE
     * @mbggenerated
     */
    public void setPhonetype(String phonetype) {
        this.phonetype = phonetype == null ? null : phonetype.trim();
    }


    public String getTcName() {
        return tcName;
    }

    public void setTcName(String tcName) {
        this.tcName = tcName;
    }
}