package com.ancun.boss.business.persistence.module;

import java.util.Date;

public class BizUserWhiteListHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_WHITE_LIST_HISTORY.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_WHITE_LIST_HISTORY.USER_TEL
     *
     * @mbggenerated
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_WHITE_LIST_HISTORY.ADD_DATE
     *
     * @mbggenerated
     */
    private Date addDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_WHITE_LIST_HISTORY.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_WHITE_LIST_HISTORY.RPCODE
     *
     * @mbggenerated
     */
    private String rpcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_WHITE_LIST_HISTORY.USERNO
     *
     * @mbggenerated
     */
    private String userno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIZ_USER_WHITE_LIST_HISTORY.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_WHITE_LIST_HISTORY.ID
     *
     * @return the value of BIZ_USER_WHITE_LIST_HISTORY.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_WHITE_LIST_HISTORY.ID
     *
     * @param id the value for BIZ_USER_WHITE_LIST_HISTORY.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_WHITE_LIST_HISTORY.USER_TEL
     *
     * @return the value of BIZ_USER_WHITE_LIST_HISTORY.USER_TEL
     *
     * @mbggenerated
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_WHITE_LIST_HISTORY.USER_TEL
     *
     * @param userTel the value for BIZ_USER_WHITE_LIST_HISTORY.USER_TEL
     *
     * @mbggenerated
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_WHITE_LIST_HISTORY.ADD_DATE
     *
     * @return the value of BIZ_USER_WHITE_LIST_HISTORY.ADD_DATE
     *
     * @mbggenerated
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_WHITE_LIST_HISTORY.ADD_DATE
     *
     * @param addDate the value for BIZ_USER_WHITE_LIST_HISTORY.ADD_DATE
     *
     * @mbggenerated
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_WHITE_LIST_HISTORY.TYPE
     *
     * @return the value of BIZ_USER_WHITE_LIST_HISTORY.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_WHITE_LIST_HISTORY.TYPE
     *
     * @param type the value for BIZ_USER_WHITE_LIST_HISTORY.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_WHITE_LIST_HISTORY.RPCODE
     *
     * @return the value of BIZ_USER_WHITE_LIST_HISTORY.RPCODE
     *
     * @mbggenerated
     */
    public String getRpcode() {
        return rpcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_WHITE_LIST_HISTORY.RPCODE
     *
     * @param rpcode the value for BIZ_USER_WHITE_LIST_HISTORY.RPCODE
     *
     * @mbggenerated
     */
    public void setRpcode(String rpcode) {
        this.rpcode = rpcode == null ? null : rpcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_WHITE_LIST_HISTORY.USERNO
     *
     * @return the value of BIZ_USER_WHITE_LIST_HISTORY.USERNO
     *
     * @mbggenerated
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_WHITE_LIST_HISTORY.USERNO
     *
     * @param userno the value for BIZ_USER_WHITE_LIST_HISTORY.USERNO
     *
     * @mbggenerated
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIZ_USER_WHITE_LIST_HISTORY.REMARK
     *
     * @return the value of BIZ_USER_WHITE_LIST_HISTORY.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIZ_USER_WHITE_LIST_HISTORY.REMARK
     *
     * @param remark the value for BIZ_USER_WHITE_LIST_HISTORY.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}