package com.ancun.boss.business.persistence.module;

import java.util.Date;

public class BizUserAuthInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIZ_USER_AUTH_INFO.ID
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIZ_USER_AUTH_INFO.USER_TEL
	 * @mbggenerated
	 */
	private String userTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIZ_USER_AUTH_INFO.AUTH_RESULT
	 * @mbggenerated
	 */
	private String authResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIZ_USER_AUTH_INFO.AUTH_DATE
	 * @mbggenerated
	 */
	private Date authDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIZ_USER_AUTH_INFO.AUTH_SOURCE
	 * @mbggenerated
	 */
	private String authSource;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIZ_USER_AUTH_INFO.ID
	 * @return  the value of BIZ_USER_AUTH_INFO.ID
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIZ_USER_AUTH_INFO.ID
	 * @param id  the value for BIZ_USER_AUTH_INFO.ID
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIZ_USER_AUTH_INFO.USER_TEL
	 * @return  the value of BIZ_USER_AUTH_INFO.USER_TEL
	 * @mbggenerated
	 */
	public String getUserTel() {
		return userTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIZ_USER_AUTH_INFO.USER_TEL
	 * @param userTel  the value for BIZ_USER_AUTH_INFO.USER_TEL
	 * @mbggenerated
	 */
	public void setUserTel(String userTel) {
		this.userTel = userTel == null ? null : userTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIZ_USER_AUTH_INFO.AUTH_RESULT
	 * @return  the value of BIZ_USER_AUTH_INFO.AUTH_RESULT
	 * @mbggenerated
	 */
	public String getAuthResult() {
		return authResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIZ_USER_AUTH_INFO.AUTH_RESULT
	 * @param authResult  the value for BIZ_USER_AUTH_INFO.AUTH_RESULT
	 * @mbggenerated
	 */
	public void setAuthResult(String authResult) {
		this.authResult = authResult == null ? null : authResult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIZ_USER_AUTH_INFO.AUTH_DATE
	 * @return  the value of BIZ_USER_AUTH_INFO.AUTH_DATE
	 * @mbggenerated
	 */
	public Date getAuthDate() {
		return authDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIZ_USER_AUTH_INFO.AUTH_DATE
	 * @param authDate  the value for BIZ_USER_AUTH_INFO.AUTH_DATE
	 * @mbggenerated
	 */
	public void setAuthDate(Date authDate) {
		this.authDate = authDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIZ_USER_AUTH_INFO.AUTH_SOURCE
	 * @return  the value of BIZ_USER_AUTH_INFO.AUTH_SOURCE
	 * @mbggenerated
	 */
	public String getAuthSource() {
		return authSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIZ_USER_AUTH_INFO.AUTH_SOURCE
	 * @param authSource  the value for BIZ_USER_AUTH_INFO.AUTH_SOURCE
	 * @mbggenerated
	 */
	public void setAuthSource(String authSource) {
		this.authSource = authSource == null ? null : authSource.trim();
	}
}