package com.ancun.boss.business.persistence.mapper;

import com.ancun.boss.business.persistence.module.BizEntInfo;
import com.ancun.boss.business.persistence.module.BizEntInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizEntInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ENT_INFO
     *
     * @mbggenerated
     */
    int countByExample(BizEntInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ENT_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(BizEntInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ENT_INFO
     *
     * @mbggenerated
     */
    int insert(BizEntInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ENT_INFO
     *
     * @mbggenerated
     */
    int insertSelective(BizEntInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ENT_INFO
     *
     * @mbggenerated
     */
    List<BizEntInfo> selectByExample(BizEntInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ENT_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizEntInfo record, @Param("example") BizEntInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_ENT_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizEntInfo record, @Param("example") BizEntInfoExample example);
}