package com.ancun.boss.business.persistence.mapper;

import com.ancun.boss.business.persistence.module.BizPersonInfo;
import com.ancun.boss.business.persistence.module.BizPersonInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BizPersonInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    int countByExample(BizPersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(BizPersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    int insert(BizPersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    int insertSelective(BizPersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    List<BizPersonInfo> selectByExample(BizPersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    BizPersonInfo selectByPrimaryKey(String userNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizPersonInfo record, @Param("example") BizPersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizPersonInfo record, @Param("example") BizPersonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizPersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PERSON_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizPersonInfo record);
}