package com.ancun.boss.business.persistence.mapper;

import com.ancun.boss.business.persistence.module.BizPreferential;
import com.ancun.boss.business.persistence.module.BizPreferentialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizPreferentialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    int countByExample(BizPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    int deleteByExample(BizPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    int insert(BizPreferential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    int insertSelective(BizPreferential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    List<BizPreferential> selectByExample(BizPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    BizPreferential selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizPreferential record, @Param("example") BizPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizPreferential record, @Param("example") BizPreferentialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizPreferential record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_PREFERENTIAL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizPreferential record);
}