package com.ancun.boss.business.persistence.mapper;

import com.ancun.boss.business.persistence.module.BizUserWhiteList;
import com.ancun.boss.business.persistence.module.BizUserWhiteListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizUserWhiteListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    int countByExample(BizUserWhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    int deleteByExample(BizUserWhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    int insert(BizUserWhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    int insertSelective(BizUserWhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    List<BizUserWhiteList> selectByExample(BizUserWhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    BizUserWhiteList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizUserWhiteList record, @Param("example") BizUserWhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizUserWhiteList record, @Param("example") BizUserWhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizUserWhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizUserWhiteList record);
}