package com.ancun.boss.business.persistence.mapper;

import com.ancun.boss.business.persistence.module.BizUserWhiteListHistory;
import com.ancun.boss.business.persistence.module.BizUserWhiteListHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizUserWhiteListHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    int countByExample(BizUserWhiteListHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(BizUserWhiteListHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    int insert(BizUserWhiteListHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(BizUserWhiteListHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    List<BizUserWhiteListHistory> selectByExample(BizUserWhiteListHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    BizUserWhiteListHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizUserWhiteListHistory record, @Param("example") BizUserWhiteListHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizUserWhiteListHistory record, @Param("example") BizUserWhiteListHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizUserWhiteListHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_WHITE_LIST_HISTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizUserWhiteListHistory record);
}