package com.ancun.boss.business.persistence.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ancun.boss.business.persistence.module.BizUserInfoQuery;
import com.ancun.boss.business.persistence.module.BizUserInfoQueryExample;

public interface BizUserInfoQueryMapper {
	
	/**删除每个用户下的重复数据*/
	int deduplicationById();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    int countByExample(BizUserInfoQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    int deleteByExample(BizUserInfoQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    int insert(BizUserInfoQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    int insertSelective(BizUserInfoQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    List<BizUserInfoQuery> selectByExample(BizUserInfoQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    BizUserInfoQuery selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizUserInfoQuery record, @Param("example") BizUserInfoQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizUserInfoQuery record, @Param("example") BizUserInfoQueryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizUserInfoQuery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_QUERY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizUserInfoQuery record);
}