package com.ancun.boss.business.persistence.mapper;

import com.ancun.boss.business.persistence.module.BizUserInfoImportFailed;
import com.ancun.boss.business.persistence.module.BizUserInfoImportFailedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizUserInfoImportFailedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    int countByExample(BizUserInfoImportFailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    int deleteByExample(BizUserInfoImportFailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    int insert(BizUserInfoImportFailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    int insertSelective(BizUserInfoImportFailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    List<BizUserInfoImportFailed> selectByExample(BizUserInfoImportFailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    BizUserInfoImportFailed selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizUserInfoImportFailed record, @Param("example") BizUserInfoImportFailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizUserInfoImportFailed record, @Param("example") BizUserInfoImportFailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizUserInfoImportFailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO_IMPORT_FAILED
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizUserInfoImportFailed record);
}