package com.ancun.boss.business.persistence.mapper;

import com.ancun.boss.business.persistence.module.BizUserInfo;
import com.ancun.boss.business.persistence.module.BizUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    int countByExample(BizUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(BizUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    int insert(BizUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    int insertSelective(BizUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    List<BizUserInfo> selectByExample(BizUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    BizUserInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BizUserInfo record, @Param("example") BizUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BizUserInfo record, @Param("example") BizUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BizUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIZ_USER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BizUserInfo record);
}