package com.ancun.boss.business.persistence.mapper;

import com.ancun.boss.business.persistence.module.BizUserAuthInfo;
import com.ancun.boss.business.persistence.module.BizUserAuthInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizUserAuthInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	int countByExample(BizUserAuthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	int deleteByExample(BizUserAuthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	int insert(BizUserAuthInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	int insertSelective(BizUserAuthInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	List<BizUserAuthInfo> selectByExample(BizUserAuthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	BizUserAuthInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") BizUserAuthInfo record,
			@Param("example") BizUserAuthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") BizUserAuthInfo record,
			@Param("example") BizUserAuthInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(BizUserAuthInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIZ_USER_AUTH_INFO
	 * @mbggenerated
	 */
	int updateByPrimaryKey(BizUserAuthInfo record);
}