package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.BlackUserInfo;
import com.ancun.boss.persistence.model.BlackUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlackUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    int countByExample(BlackUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(BlackUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    int insert(BlackUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    int insertSelective(BlackUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    List<BlackUserInfo> selectByExample(BlackUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    BlackUserInfo selectByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BlackUserInfo record, @Param("example") BlackUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BlackUserInfo record, @Param("example") BlackUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BlackUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLACK_USER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BlackUserInfo record);
}