package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.CallQualityInfo;
import com.ancun.boss.persistence.model.CallQualityInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CallQualityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    int countByExample(CallQualityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(CallQualityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    int insert(CallQualityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    int insertSelective(CallQualityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    List<CallQualityInfo> selectByExample(CallQualityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    CallQualityInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CallQualityInfo record, @Param("example") CallQualityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CallQualityInfo record, @Param("example") CallQualityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CallQualityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_QUALITY_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CallQualityInfo record);
}