package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.CalledVoice;
import com.ancun.boss.persistence.model.CalledVoiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalledVoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    int countByExample(CalledVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    int deleteByExample(CalledVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    int insert(CalledVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    int insertSelective(CalledVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    List<CalledVoice> selectByExample(CalledVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    CalledVoice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CalledVoice record, @Param("example") CalledVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CalledVoice record, @Param("example") CalledVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CalledVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALLED_VOICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CalledVoice record);
}