package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.CallInRecord;
import com.ancun.boss.persistence.model.CallInRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CallInRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    int countByExample(CallInRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    int deleteByExample(CallInRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    int insert(CallInRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    int insertSelective(CallInRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    List<CallInRecord> selectByExample(CallInRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    CallInRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CallInRecord record, @Param("example") CallInRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CallInRecord record, @Param("example") CallInRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CallInRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CallInRecord record);
}