package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.CallInVoice;
import com.ancun.boss.persistence.model.CallInVoiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CallInVoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    int countByExample(CallInVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    int deleteByExample(CallInVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    int insert(CallInVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    int insertSelective(CallInVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    List<CallInVoice> selectByExample(CallInVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    CallInVoice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CallInVoice record, @Param("example") CallInVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CallInVoice record, @Param("example") CallInVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CallInVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CALL_IN_VOICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CallInVoice record);
}