package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.CancelRecord;
import com.ancun.boss.persistence.model.CancelRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CancelRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    int countByExample(CancelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    int deleteByExample(CancelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    int insert(CancelRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    int insertSelective(CancelRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    List<CancelRecord> selectByExample(CancelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    CancelRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CancelRecord record, @Param("example") CancelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CancelRecord record, @Param("example") CancelRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CancelRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CANCEL_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CancelRecord record);
}