package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.FunctionInfo;
import com.ancun.boss.persistence.model.FunctionInfoExample;
import com.ancun.boss.persistence.model.MenuFunctionInfo;
import com.ancun.boss.persistence.model.RoleMenuFunction;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FunctionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    int countByExample(FunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(FunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fucno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    int insert(FunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    int insertSelective(FunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    List<FunctionInfo> selectByExample(FunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    FunctionInfo selectByPrimaryKey(String fucno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FunctionInfo record, @Param("example") FunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FunctionInfo record, @Param("example") FunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUNCTION_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FunctionInfo record);
    
    public List<FunctionInfo> selectSerialFunctionInfoByRoleMenuFunction(
			RoleMenuFunction roleMenuFunction);
    
    public List<FunctionInfo> selectSerialFunctionInfoByMenuFunction(
			MenuFunctionInfo menuFunctionInfo);
}