package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.ImportFailedRecord;
import com.ancun.boss.persistence.model.ImportFailedRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImportFailedRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    int countByExample(ImportFailedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    int deleteByExample(ImportFailedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    int insert(ImportFailedRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    int insertSelective(ImportFailedRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    List<ImportFailedRecord> selectByExample(ImportFailedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    ImportFailedRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ImportFailedRecord record, @Param("example") ImportFailedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ImportFailedRecord record, @Param("example") ImportFailedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImportFailedRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IMPORT_FAILED_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImportFailedRecord record);
}