package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.MenuFunctionInfo;
import com.ancun.boss.persistence.model.MenuFunctionInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuFunctionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU_FUNCTION_INFO
     *
     * @mbggenerated
     */
    int countByExample(MenuFunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU_FUNCTION_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(MenuFunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU_FUNCTION_INFO
     *
     * @mbggenerated
     */
    int insert(MenuFunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU_FUNCTION_INFO
     *
     * @mbggenerated
     */
    int insertSelective(MenuFunctionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU_FUNCTION_INFO
     *
     * @mbggenerated
     */
    List<MenuFunctionInfo> selectByExample(MenuFunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU_FUNCTION_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MenuFunctionInfo record, @Param("example") MenuFunctionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU_FUNCTION_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MenuFunctionInfo record, @Param("example") MenuFunctionInfoExample example);
}