package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.PhoneDivid;
import com.ancun.boss.persistence.model.PhoneDividExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhoneDividMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    int countByExample(PhoneDividExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    int deleteByExample(PhoneDividExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    int insert(PhoneDivid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    int insertSelective(PhoneDivid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    List<PhoneDivid> selectByExample(PhoneDividExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    PhoneDivid selectByPrimaryKey(Integer phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PhoneDivid record, @Param("example") PhoneDividExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PhoneDivid record, @Param("example") PhoneDividExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhoneDivid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_DIVID
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhoneDivid record);
}