package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.PhoneSourceHelp;
import com.ancun.boss.persistence.model.PhoneSourceHelpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhoneSourceHelpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    int countByExample(PhoneSourceHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    int deleteByExample(PhoneSourceHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    int insert(PhoneSourceHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    int insertSelective(PhoneSourceHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    List<PhoneSourceHelp> selectByExample(PhoneSourceHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    PhoneSourceHelp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PhoneSourceHelp record, @Param("example") PhoneSourceHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PhoneSourceHelp record, @Param("example") PhoneSourceHelpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhoneSourceHelp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_SOURCE_HELP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhoneSourceHelp record);
}