package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.PhoneRepository;
import com.ancun.boss.persistence.model.PhoneRepositoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhoneRepositoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    int countByExample(PhoneRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    int deleteByExample(PhoneRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    int insert(PhoneRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    int insertSelective(PhoneRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    List<PhoneRepository> selectByExample(PhoneRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    PhoneRepository selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PhoneRepository record, @Param("example") PhoneRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PhoneRepository record, @Param("example") PhoneRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhoneRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHONE_REPOSITORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhoneRepository record);
}