package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.RoleMenuFunction;
import com.ancun.boss.persistence.model.RoleMenuFunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMenuFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_MENU_FUNCTION
     *
     * @mbggenerated
     */
    int countByExample(RoleMenuFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_MENU_FUNCTION
     *
     * @mbggenerated
     */
    int deleteByExample(RoleMenuFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_MENU_FUNCTION
     *
     * @mbggenerated
     */
    int insert(RoleMenuFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_MENU_FUNCTION
     *
     * @mbggenerated
     */
    int insertSelective(RoleMenuFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_MENU_FUNCTION
     *
     * @mbggenerated
     */
    List<RoleMenuFunction> selectByExample(RoleMenuFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_MENU_FUNCTION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoleMenuFunction record, @Param("example") RoleMenuFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE_MENU_FUNCTION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoleMenuFunction record, @Param("example") RoleMenuFunctionExample example);
}