package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.SystemUserInfo;
import com.ancun.boss.persistence.model.SystemUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    int countByExample(SystemUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(SystemUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    int insert(SystemUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    int insertSelective(SystemUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    List<SystemUserInfo> selectByExample(SystemUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    SystemUserInfo selectByPrimaryKey(String userno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemUserInfo record, @Param("example") SystemUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemUserInfo record, @Param("example") SystemUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_USER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemUserInfo record);
}