package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.SystemBasicConfig;
import com.ancun.boss.persistence.model.SystemBasicConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemBasicConfigMapper {
	List<SystemBasicConfig> selectDistinctMoudle();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    int countByExample(SystemBasicConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    int deleteByExample(SystemBasicConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer basicno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    int insert(SystemBasicConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    int insertSelective(SystemBasicConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    List<SystemBasicConfig> selectByExample(SystemBasicConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    SystemBasicConfig selectByPrimaryKey(Integer basicno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemBasicConfig record, @Param("example") SystemBasicConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemBasicConfig record, @Param("example") SystemBasicConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemBasicConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_BASIC_CONFIG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemBasicConfig record);
}