package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.SystemNotice;
import com.ancun.boss.persistence.model.SystemNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    int countByExample(SystemNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    int deleteByExample(SystemNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    int insert(SystemNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    int insertSelective(SystemNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    List<SystemNotice> selectByExample(SystemNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    SystemNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemNotice record, @Param("example") SystemNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemNotice record, @Param("example") SystemNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NOTICE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemNotice record);
}