package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.SystemRoleInfo;
import com.ancun.boss.persistence.model.SystemRoleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemRoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    int countByExample(SystemRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(SystemRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    int insert(SystemRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    int insertSelective(SystemRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    List<SystemRoleInfo> selectByExample(SystemRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    SystemRoleInfo selectByPrimaryKey(String roleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemRoleInfo record, @Param("example") SystemRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemRoleInfo record, @Param("example") SystemRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemRoleInfo record);
}