package com.ancun.boss.persistence.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.ancun.boss.persistence.model.SystemMenuInfo;
import com.ancun.boss.persistence.model.SystemMenuInfoExample;

public interface SystemMenuInfoMapper {
	/**更新树形的排序*/
	int updatePoplarOrdered(Map<String,Long> map);
	/**更新树形的最大叶子数。叶子增加叶子用*/
	int updatePoplarMaxleaf(Map<String,Long> map);
	/**更新树形的最大叶子数,除了最小的兄弟。结点增加叶子用*/
	int updatePoplarMaxleafExceptLittleBrother(Map<String,Long> map);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    int countByExample(SystemMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(SystemMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String menuno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    int insert(SystemMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    int insertSelective(SystemMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    List<SystemMenuInfo> selectByExample(SystemMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    SystemMenuInfo selectByPrimaryKey(String menuno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemMenuInfo record, @Param("example") SystemMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemMenuInfo record, @Param("example") SystemMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemMenuInfo record);
}