package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.UserDatapermission;
import com.ancun.boss.persistence.model.UserDatapermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDatapermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    int countByExample(UserDatapermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    int deleteByExample(UserDatapermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    int insert(UserDatapermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    int insertSelective(UserDatapermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    List<UserDatapermission> selectByExample(UserDatapermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    UserDatapermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserDatapermission record, @Param("example") UserDatapermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserDatapermission record, @Param("example") UserDatapermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDatapermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_DATAPERMISSION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDatapermission record);
}