package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.UserWorkOrderInfo;
import com.ancun.boss.persistence.model.UserWorkOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserWorkOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    int countByExample(UserWorkOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    int deleteByExample(UserWorkOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    int insert(UserWorkOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    int insertSelective(UserWorkOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    List<UserWorkOrderInfo> selectByExample(UserWorkOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    UserWorkOrderInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserWorkOrderInfo record, @Param("example") UserWorkOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserWorkOrderInfo record, @Param("example") UserWorkOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserWorkOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_WORK_ORDER_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserWorkOrderInfo record);
}