package com.ancun.boss.persistence.mapper;

import com.ancun.boss.persistence.model.WorkOrderVisitRecord;
import com.ancun.boss.persistence.model.WorkOrderVisitRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkOrderVisitRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    int countByExample(WorkOrderVisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    int deleteByExample(WorkOrderVisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    int insert(WorkOrderVisitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    int insertSelective(WorkOrderVisitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    List<WorkOrderVisitRecord> selectByExample(WorkOrderVisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    WorkOrderVisitRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WorkOrderVisitRecord record, @Param("example") WorkOrderVisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WorkOrderVisitRecord record, @Param("example") WorkOrderVisitRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkOrderVisitRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_ORDER_VISIT_RECORD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkOrderVisitRecord record);
}