package com.ancun.boss.persistence.model;

public class FunctionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUNCTION_INFO.FUCNO
     *
     * @mbggenerated
     */
    private String fucno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUNCTION_INFO.FUCNAME
     *
     * @mbggenerated
     */
    private String fucname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUNCTION_INFO.FUCSTYLE
     *
     * @mbggenerated
     */
    private String fucstyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUNCTION_INFO.DELETED
     *
     * @mbggenerated
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUNCTION_INFO.FUCNO
     *
     * @return the value of FUNCTION_INFO.FUCNO
     *
     * @mbggenerated
     */
    public String getFucno() {
        return fucno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUNCTION_INFO.FUCNO
     *
     * @param fucno the value for FUNCTION_INFO.FUCNO
     *
     * @mbggenerated
     */
    public void setFucno(String fucno) {
        this.fucno = fucno == null ? null : fucno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUNCTION_INFO.FUCNAME
     *
     * @return the value of FUNCTION_INFO.FUCNAME
     *
     * @mbggenerated
     */
    public String getFucname() {
        return fucname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUNCTION_INFO.FUCNAME
     *
     * @param fucname the value for FUNCTION_INFO.FUCNAME
     *
     * @mbggenerated
     */
    public void setFucname(String fucname) {
        this.fucname = fucname == null ? null : fucname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUNCTION_INFO.FUCSTYLE
     *
     * @return the value of FUNCTION_INFO.FUCSTYLE
     *
     * @mbggenerated
     */
    public String getFucstyle() {
        return fucstyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUNCTION_INFO.FUCSTYLE
     *
     * @param fucstyle the value for FUNCTION_INFO.FUCSTYLE
     *
     * @mbggenerated
     */
    public void setFucstyle(String fucstyle) {
        this.fucstyle = fucstyle == null ? null : fucstyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUNCTION_INFO.DELETED
     *
     * @return the value of FUNCTION_INFO.DELETED
     *
     * @mbggenerated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUNCTION_INFO.DELETED
     *
     * @param deleted the value for FUNCTION_INFO.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * 是否已选中 add by mif
     */
    private boolean ischecked;

    public boolean ischecked() {
        return ischecked;
    }

    public void setIschecked(boolean ischecked) {
        this.ischecked = ischecked;
    }
}