package com.ancun.boss.persistence.model;

import java.util.Date;

public class PhoneSourceHelp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHONE_SOURCE_HELP.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHONE_SOURCE_HELP.BIZ_NAME
     *
     * @mbggenerated
     */
    private String bizName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHONE_SOURCE_HELP.GET_TIME
     *
     * @mbggenerated
     */
    private Date getTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PHONE_SOURCE_HELP.PHONE_SOURCE
     *
     * @mbggenerated
     */
    private String phoneSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHONE_SOURCE_HELP.ID
     *
     * @return the value of PHONE_SOURCE_HELP.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHONE_SOURCE_HELP.ID
     *
     * @param id the value for PHONE_SOURCE_HELP.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHONE_SOURCE_HELP.BIZ_NAME
     *
     * @return the value of PHONE_SOURCE_HELP.BIZ_NAME
     *
     * @mbggenerated
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHONE_SOURCE_HELP.BIZ_NAME
     *
     * @param bizName the value for PHONE_SOURCE_HELP.BIZ_NAME
     *
     * @mbggenerated
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHONE_SOURCE_HELP.GET_TIME
     *
     * @return the value of PHONE_SOURCE_HELP.GET_TIME
     *
     * @mbggenerated
     */
    public Date getGetTime() {
        return getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHONE_SOURCE_HELP.GET_TIME
     *
     * @param getTime the value for PHONE_SOURCE_HELP.GET_TIME
     *
     * @mbggenerated
     */
    public void setGetTime(Date getTime) {
        this.getTime = getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PHONE_SOURCE_HELP.PHONE_SOURCE
     *
     * @return the value of PHONE_SOURCE_HELP.PHONE_SOURCE
     *
     * @mbggenerated
     */
    public String getPhoneSource() {
        return phoneSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PHONE_SOURCE_HELP.PHONE_SOURCE
     *
     * @param phoneSource the value for PHONE_SOURCE_HELP.PHONE_SOURCE
     *
     * @mbggenerated
     */
    public void setPhoneSource(String phoneSource) {
        this.phoneSource = phoneSource == null ? null : phoneSource.trim();
    }
}