package com.ancun.boss.persistence.model;

import java.util.Date;

import com.ancun.boss.pojo.BossBasePojo;

public class SystemUserInfo extends BossBasePojo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.USERNO
     *
     * @mbggenerated
     */
    private String userno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.PWD
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.ORGNO
     *
     * @mbggenerated
     */
    private String orgno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.CONTACTPHONE
     *
     * @mbggenerated
     */
    private String contactphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.DELETED
     *
     * @mbggenerated
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.DATAPERMISSION
     *
     * @mbggenerated
     */
    private String datapermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.LOGINTIME
     *
     * @mbggenerated
     */
    private Date logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.ERRTIMES
     *
     * @mbggenerated
     */
    private Long errtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.SPELL
     *
     * @mbggenerated
     */
    private String spell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM_USER_INFO.JOB
     *
     * @mbggenerated
     */
    private String job;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.USERNO
     *
     * @return the value of SYSTEM_USER_INFO.USERNO
     *
     * @mbggenerated
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.USERNO
     *
     * @param userno the value for SYSTEM_USER_INFO.USERNO
     *
     * @mbggenerated
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.PWD
     *
     * @return the value of SYSTEM_USER_INFO.PWD
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.PWD
     *
     * @param pwd the value for SYSTEM_USER_INFO.PWD
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.USERNAME
     *
     * @return the value of SYSTEM_USER_INFO.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.USERNAME
     *
     * @param username the value for SYSTEM_USER_INFO.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.ORGNO
     *
     * @return the value of SYSTEM_USER_INFO.ORGNO
     *
     * @mbggenerated
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.ORGNO
     *
     * @param orgno the value for SYSTEM_USER_INFO.ORGNO
     *
     * @mbggenerated
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno == null ? null : orgno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.CONTACTPHONE
     *
     * @return the value of SYSTEM_USER_INFO.CONTACTPHONE
     *
     * @mbggenerated
     */
    public String getContactphone() {
        return contactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.CONTACTPHONE
     *
     * @param contactphone the value for SYSTEM_USER_INFO.CONTACTPHONE
     *
     * @mbggenerated
     */
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone == null ? null : contactphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.EMAIL
     *
     * @return the value of SYSTEM_USER_INFO.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.EMAIL
     *
     * @param email the value for SYSTEM_USER_INFO.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.REMARK
     *
     * @return the value of SYSTEM_USER_INFO.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.REMARK
     *
     * @param remark the value for SYSTEM_USER_INFO.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.DELETED
     *
     * @return the value of SYSTEM_USER_INFO.DELETED
     *
     * @mbggenerated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.DELETED
     *
     * @param deleted the value for SYSTEM_USER_INFO.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.DATAPERMISSION
     *
     * @return the value of SYSTEM_USER_INFO.DATAPERMISSION
     *
     * @mbggenerated
     */
    public String getDatapermission() {
        return datapermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.DATAPERMISSION
     *
     * @param datapermission the value for SYSTEM_USER_INFO.DATAPERMISSION
     *
     * @mbggenerated
     */
    public void setDatapermission(String datapermission) {
        this.datapermission = datapermission == null ? null : datapermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.LOGINTIME
     *
     * @return the value of SYSTEM_USER_INFO.LOGINTIME
     *
     * @mbggenerated
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.LOGINTIME
     *
     * @param logintime the value for SYSTEM_USER_INFO.LOGINTIME
     *
     * @mbggenerated
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.ERRTIMES
     *
     * @return the value of SYSTEM_USER_INFO.ERRTIMES
     *
     * @mbggenerated
     */
    public Long getErrtimes() {
        return errtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.ERRTIMES
     *
     * @param errtimes the value for SYSTEM_USER_INFO.ERRTIMES
     *
     * @mbggenerated
     */
    public void setErrtimes(Long errtimes) {
        this.errtimes = errtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.SPELL
     *
     * @return the value of SYSTEM_USER_INFO.SPELL
     *
     * @mbggenerated
     */
    public String getSpell() {
        return spell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.SPELL
     *
     * @param spell the value for SYSTEM_USER_INFO.SPELL
     *
     * @mbggenerated
     */
    public void setSpell(String spell) {
        this.spell = spell == null ? null : spell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM_USER_INFO.JOB
     *
     * @return the value of SYSTEM_USER_INFO.JOB
     *
     * @mbggenerated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM_USER_INFO.JOB
     *
     * @param job the value for SYSTEM_USER_INFO.JOB
     *
     * @mbggenerated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }
}