package com.ancun.boss.persistence.model;

import java.util.ArrayList;
import java.util.List;

public class SystemMenuInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public SystemMenuInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMenunoIsNull() {
            addCriterion("MENUNO is null");
            return (Criteria) this;
        }

        public Criteria andMenunoIsNotNull() {
            addCriterion("MENUNO is not null");
            return (Criteria) this;
        }

        public Criteria andMenunoEqualTo(String value) {
            addCriterion("MENUNO =", value, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoNotEqualTo(String value) {
            addCriterion("MENUNO <>", value, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoGreaterThan(String value) {
            addCriterion("MENUNO >", value, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoGreaterThanOrEqualTo(String value) {
            addCriterion("MENUNO >=", value, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoLessThan(String value) {
            addCriterion("MENUNO <", value, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoLessThanOrEqualTo(String value) {
            addCriterion("MENUNO <=", value, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoLike(String value) {
            addCriterion("MENUNO like", value, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoNotLike(String value) {
            addCriterion("MENUNO not like", value, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoIn(List<String> values) {
            addCriterion("MENUNO in", values, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoNotIn(List<String> values) {
            addCriterion("MENUNO not in", values, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoBetween(String value1, String value2) {
            addCriterion("MENUNO between", value1, value2, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunoNotBetween(String value1, String value2) {
            addCriterion("MENUNO not between", value1, value2, "menuno");
            return (Criteria) this;
        }

        public Criteria andMenunameIsNull() {
            addCriterion("MENUNAME is null");
            return (Criteria) this;
        }

        public Criteria andMenunameIsNotNull() {
            addCriterion("MENUNAME is not null");
            return (Criteria) this;
        }

        public Criteria andMenunameEqualTo(String value) {
            addCriterion("MENUNAME =", value, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameNotEqualTo(String value) {
            addCriterion("MENUNAME <>", value, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameGreaterThan(String value) {
            addCriterion("MENUNAME >", value, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameGreaterThanOrEqualTo(String value) {
            addCriterion("MENUNAME >=", value, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameLessThan(String value) {
            addCriterion("MENUNAME <", value, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameLessThanOrEqualTo(String value) {
            addCriterion("MENUNAME <=", value, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameLike(String value) {
            addCriterion("MENUNAME like", value, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameNotLike(String value) {
            addCriterion("MENUNAME not like", value, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameIn(List<String> values) {
            addCriterion("MENUNAME in", values, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameNotIn(List<String> values) {
            addCriterion("MENUNAME not in", values, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameBetween(String value1, String value2) {
            addCriterion("MENUNAME between", value1, value2, "menuname");
            return (Criteria) this;
        }

        public Criteria andMenunameNotBetween(String value1, String value2) {
            addCriterion("MENUNAME not between", value1, value2, "menuname");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoIsNull() {
            addCriterion("PMENUINFO is null");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoIsNotNull() {
            addCriterion("PMENUINFO is not null");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoEqualTo(String value) {
            addCriterion("PMENUINFO =", value, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoNotEqualTo(String value) {
            addCriterion("PMENUINFO <>", value, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoGreaterThan(String value) {
            addCriterion("PMENUINFO >", value, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoGreaterThanOrEqualTo(String value) {
            addCriterion("PMENUINFO >=", value, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoLessThan(String value) {
            addCriterion("PMENUINFO <", value, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoLessThanOrEqualTo(String value) {
            addCriterion("PMENUINFO <=", value, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoLike(String value) {
            addCriterion("PMENUINFO like", value, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoNotLike(String value) {
            addCriterion("PMENUINFO not like", value, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoIn(List<String> values) {
            addCriterion("PMENUINFO in", values, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoNotIn(List<String> values) {
            addCriterion("PMENUINFO not in", values, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoBetween(String value1, String value2) {
            addCriterion("PMENUINFO between", value1, value2, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andPmenuinfoNotBetween(String value1, String value2) {
            addCriterion("PMENUINFO not between", value1, value2, "pmenuinfo");
            return (Criteria) this;
        }

        public Criteria andMenuurlIsNull() {
            addCriterion("MENUURL is null");
            return (Criteria) this;
        }

        public Criteria andMenuurlIsNotNull() {
            addCriterion("MENUURL is not null");
            return (Criteria) this;
        }

        public Criteria andMenuurlEqualTo(String value) {
            addCriterion("MENUURL =", value, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlNotEqualTo(String value) {
            addCriterion("MENUURL <>", value, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlGreaterThan(String value) {
            addCriterion("MENUURL >", value, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlGreaterThanOrEqualTo(String value) {
            addCriterion("MENUURL >=", value, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlLessThan(String value) {
            addCriterion("MENUURL <", value, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlLessThanOrEqualTo(String value) {
            addCriterion("MENUURL <=", value, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlLike(String value) {
            addCriterion("MENUURL like", value, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlNotLike(String value) {
            addCriterion("MENUURL not like", value, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlIn(List<String> values) {
            addCriterion("MENUURL in", values, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlNotIn(List<String> values) {
            addCriterion("MENUURL not in", values, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlBetween(String value1, String value2) {
            addCriterion("MENUURL between", value1, value2, "menuurl");
            return (Criteria) this;
        }

        public Criteria andMenuurlNotBetween(String value1, String value2) {
            addCriterion("MENUURL not between", value1, value2, "menuurl");
            return (Criteria) this;
        }

        public Criteria andModuleIsNull() {
            addCriterion("MODULE is null");
            return (Criteria) this;
        }

        public Criteria andModuleIsNotNull() {
            addCriterion("MODULE is not null");
            return (Criteria) this;
        }

        public Criteria andModuleEqualTo(String value) {
            addCriterion("MODULE =", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleNotEqualTo(String value) {
            addCriterion("MODULE <>", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleGreaterThan(String value) {
            addCriterion("MODULE >", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleGreaterThanOrEqualTo(String value) {
            addCriterion("MODULE >=", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleLessThan(String value) {
            addCriterion("MODULE <", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleLessThanOrEqualTo(String value) {
            addCriterion("MODULE <=", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleLike(String value) {
            addCriterion("MODULE like", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleNotLike(String value) {
            addCriterion("MODULE not like", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleIn(List<String> values) {
            addCriterion("MODULE in", values, "module");
            return (Criteria) this;
        }

        public Criteria andModuleNotIn(List<String> values) {
            addCriterion("MODULE not in", values, "module");
            return (Criteria) this;
        }

        public Criteria andModuleBetween(String value1, String value2) {
            addCriterion("MODULE between", value1, value2, "module");
            return (Criteria) this;
        }

        public Criteria andModuleNotBetween(String value1, String value2) {
            addCriterion("MODULE not between", value1, value2, "module");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("DELETED is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(String value) {
            addCriterion("DELETED =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(String value) {
            addCriterion("DELETED <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(String value) {
            addCriterion("DELETED >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("DELETED >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(String value) {
            addCriterion("DELETED <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(String value) {
            addCriterion("DELETED <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLike(String value) {
            addCriterion("DELETED like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotLike(String value) {
            addCriterion("DELETED not like", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<String> values) {
            addCriterion("DELETED in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<String> values) {
            addCriterion("DELETED not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(String value1, String value2) {
            addCriterion("DELETED between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(String value1, String value2) {
            addCriterion("DELETED not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andSpellIsNull() {
            addCriterion("SPELL is null");
            return (Criteria) this;
        }

        public Criteria andSpellIsNotNull() {
            addCriterion("SPELL is not null");
            return (Criteria) this;
        }

        public Criteria andSpellEqualTo(String value) {
            addCriterion("SPELL =", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellNotEqualTo(String value) {
            addCriterion("SPELL <>", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellGreaterThan(String value) {
            addCriterion("SPELL >", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellGreaterThanOrEqualTo(String value) {
            addCriterion("SPELL >=", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellLessThan(String value) {
            addCriterion("SPELL <", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellLessThanOrEqualTo(String value) {
            addCriterion("SPELL <=", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellLike(String value) {
            addCriterion("SPELL like", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellNotLike(String value) {
            addCriterion("SPELL not like", value, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellIn(List<String> values) {
            addCriterion("SPELL in", values, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellNotIn(List<String> values) {
            addCriterion("SPELL not in", values, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellBetween(String value1, String value2) {
            addCriterion("SPELL between", value1, value2, "spell");
            return (Criteria) this;
        }

        public Criteria andSpellNotBetween(String value1, String value2) {
            addCriterion("SPELL not between", value1, value2, "spell");
            return (Criteria) this;
        }

        public Criteria andOrderedIsNull() {
            addCriterion("ORDERED is null");
            return (Criteria) this;
        }

        public Criteria andOrderedIsNotNull() {
            addCriterion("ORDERED is not null");
            return (Criteria) this;
        }

        public Criteria andOrderedEqualTo(Long value) {
            addCriterion("ORDERED =", value, "ordered");
            return (Criteria) this;
        }

        public Criteria andOrderedNotEqualTo(Long value) {
            addCriterion("ORDERED <>", value, "ordered");
            return (Criteria) this;
        }

        public Criteria andOrderedGreaterThan(Long value) {
            addCriterion("ORDERED >", value, "ordered");
            return (Criteria) this;
        }

        public Criteria andOrderedGreaterThanOrEqualTo(Long value) {
            addCriterion("ORDERED >=", value, "ordered");
            return (Criteria) this;
        }

        public Criteria andOrderedLessThan(Long value) {
            addCriterion("ORDERED <", value, "ordered");
            return (Criteria) this;
        }

        public Criteria andOrderedLessThanOrEqualTo(Long value) {
            addCriterion("ORDERED <=", value, "ordered");
            return (Criteria) this;
        }

        public Criteria andOrderedIn(List<Long> values) {
            addCriterion("ORDERED in", values, "ordered");
            return (Criteria) this;
        }

        public Criteria andOrderedNotIn(List<Long> values) {
            addCriterion("ORDERED not in", values, "ordered");
            return (Criteria) this;
        }

        public Criteria andOrderedBetween(Long value1, Long value2) {
            addCriterion("ORDERED between", value1, value2, "ordered");
            return (Criteria) this;
        }

        public Criteria andOrderedNotBetween(Long value1, Long value2) {
            addCriterion("ORDERED not between", value1, value2, "ordered");
            return (Criteria) this;
        }

        public Criteria andMaxleafIsNull() {
            addCriterion("MAXLEAF is null");
            return (Criteria) this;
        }

        public Criteria andMaxleafIsNotNull() {
            addCriterion("MAXLEAF is not null");
            return (Criteria) this;
        }

        public Criteria andMaxleafEqualTo(Long value) {
            addCriterion("MAXLEAF =", value, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andMaxleafNotEqualTo(Long value) {
            addCriterion("MAXLEAF <>", value, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andMaxleafGreaterThan(Long value) {
            addCriterion("MAXLEAF >", value, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andMaxleafGreaterThanOrEqualTo(Long value) {
            addCriterion("MAXLEAF >=", value, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andMaxleafLessThan(Long value) {
            addCriterion("MAXLEAF <", value, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andMaxleafLessThanOrEqualTo(Long value) {
            addCriterion("MAXLEAF <=", value, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andMaxleafIn(List<Long> values) {
            addCriterion("MAXLEAF in", values, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andMaxleafNotIn(List<Long> values) {
            addCriterion("MAXLEAF not in", values, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andMaxleafBetween(Long value1, Long value2) {
            addCriterion("MAXLEAF between", value1, value2, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andMaxleafNotBetween(Long value1, Long value2) {
            addCriterion("MAXLEAF not between", value1, value2, "maxleaf");
            return (Criteria) this;
        }

        public Criteria andLeveledIsNull() {
            addCriterion("LEVELED is null");
            return (Criteria) this;
        }

        public Criteria andLeveledIsNotNull() {
            addCriterion("LEVELED is not null");
            return (Criteria) this;
        }

        public Criteria andLeveledEqualTo(Long value) {
            addCriterion("LEVELED =", value, "leveled");
            return (Criteria) this;
        }

        public Criteria andLeveledNotEqualTo(Long value) {
            addCriterion("LEVELED <>", value, "leveled");
            return (Criteria) this;
        }

        public Criteria andLeveledGreaterThan(Long value) {
            addCriterion("LEVELED >", value, "leveled");
            return (Criteria) this;
        }

        public Criteria andLeveledGreaterThanOrEqualTo(Long value) {
            addCriterion("LEVELED >=", value, "leveled");
            return (Criteria) this;
        }

        public Criteria andLeveledLessThan(Long value) {
            addCriterion("LEVELED <", value, "leveled");
            return (Criteria) this;
        }

        public Criteria andLeveledLessThanOrEqualTo(Long value) {
            addCriterion("LEVELED <=", value, "leveled");
            return (Criteria) this;
        }

        public Criteria andLeveledIn(List<Long> values) {
            addCriterion("LEVELED in", values, "leveled");
            return (Criteria) this;
        }

        public Criteria andLeveledNotIn(List<Long> values) {
            addCriterion("LEVELED not in", values, "leveled");
            return (Criteria) this;
        }

        public Criteria andLeveledBetween(Long value1, Long value2) {
            addCriterion("LEVELED between", value1, value2, "leveled");
            return (Criteria) this;
        }

        public Criteria andLeveledNotBetween(Long value1, Long value2) {
            addCriterion("LEVELED not between", value1, value2, "leveled");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYSTEM_MENU_INFO
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}