package com.ancun.boss.persistence.model;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.USERNO
     *
     * @mbggenerated
     */
    private String userno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.ROLENO
     *
     * @mbggenerated
     */
    private String roleno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.USERNO
     *
     * @return the value of USER_ROLE.USERNO
     *
     * @mbggenerated
     */
    public String getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.USERNO
     *
     * @param userno the value for USER_ROLE.USERNO
     *
     * @mbggenerated
     */
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.ROLENO
     *
     * @return the value of USER_ROLE.ROLENO
     *
     * @mbggenerated
     */
    public String getRoleno() {
        return roleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.ROLENO
     *
     * @param roleno the value for USER_ROLE.ROLENO
     *
     * @mbggenerated
     */
    public void setRoleno(String roleno) {
        this.roleno = roleno == null ? null : roleno.trim();
    }
}